name: Sync between main and pages

on:
  push:
    branches:
      - main
    paths:
      - 'newicons/appfilter.xml'
  workflow_dispatch:
    inputs:
        run_fetch_and_push_file:
            description: 'Set to true to run the fetch and push file job'
            required: false
            default: true
            type: boolean

jobs:
  fetch_and_push_file:
    name: Fetch and Push File
    if: ${{ github.repository == vars.REPOSITORY && ((github.event_name == 'push' && github.ref_name == vars.MAIN_BRANCH) || (github.event_name == 'workflow_dispatch' && inputs.run_fetch_and_push_file == true)) }}
    runs-on: codeberg-tiny
    concurrency:
      group: push
      cancel-in-progress: false
    permissions:
      contents: write
    environment:
      name: FileSync
    env:
      SOURCE_BRANCH: ${{vars.MAIN_BRANCH}}
      TARGET_BRANCH: ${{vars.PAGES_BRANCH}}
      FILE_PATH: newicons/appfilter.xml
    steps:
      # Step 1: Checkout the repository
      - name: Checkout main Repository
        uses: actions/checkout@v5
        with:
          ref: ${{vars.MAIN_BRANCH}}
          path: main
      - name: Checkout Arcticons-Pages Repository
        # Step 2: Checkout the 2. repository

        uses: actions/checkout@v5
        with:
          ref: ${{vars.PAGES_BRANCH}}
          path: pages
      - name: Copy File from main to Arcticons-Pages
        # Step 3: Fetch the file from the source branch

        run: |
          rm pages/newicons/appfilter.xml
          cp main/newicons/appfilter.xml pages/newicons/appfilter.xml
      - name: Commit and Push Changes
        # Step 4: Commit and push changes

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd pages
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add $FILE_PATH
          git commit -m "Update $FILE_PATH from $SOURCE_BRANCH to $TARGET_BRANCH"
          git push    